// Generated by CoffeeScript 1.10.0
(function() {
  var assert;

  assert = chai.assert;

  describe('deck', function() {
    var deck, hand;
    deck = null;
    hand = null;
    beforeEach(function() {
      deck = new Deck();
      console.log('before', deck);
      return hand = deck.dealPlayer();
    });
    return describe('hit', function() {
      return it('should give the last card from the deck', function() {
        console.log('after hit', deck);
        assert.strictEqual(deck.get('length', 50));
        console.log('last', deck.last());
        assert.strictEqual(deck.last(), hand.hit());
        return assert.strictEqual(deck.get('length', 49));
      });
    });
  });

}).call(this);

//# sourceMappingURL=DeckSpec.js.map
